Putilin2018/Models/ViewРасходГСМ.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Putilin2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewРасходГСМ
    {
        public string Название_группы { get; set; }
        public string Название_задачи { get; set; }
        public System.DateTime Дата_рейса { get; set; }
        public int Расход_ГСМ { get; set; }
        public int Группа_задачID { get; set; }
        public int РейсID { get; set; }
        public int ЗадачаID { get; set; }
    }
}

Putilin2018/Controllers/ViewРасходГСМController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Putilin2018.Models;

namespace Putilin2018.Controllers
{
    public class ViewРасходГСМController : Controller
    {
        private MyDatabaseEntities db = new MyDatabaseEntities();

        [HttpPost]
        // GET: ViewРасходГСМ
        public ActionResult Index(FormCollection collection)
        {            
            DateTime date_start = (collection["date_start"]==null) ? DateTime.Now : Convert.ToDateTime(collection["date_start"]);
            DateTime date_end = (collection["date_end"] == null) ? DateTime.Now : Convert.ToDateTime(collection["date_end"]);

            ViewBag.date_start = "" + (date_start.Day < 10 ? "0" : "") + date_start.Day + "." + (date_start.Month < 10 ? "0" : "") + date_start.Month + "." + date_start.Year;
            ViewBag.date_end = "" + (date_end.Day < 10 ? "0" : "") + date_end.Day + "." + (date_end.Month < 10 ? "0" : "") + date_end.Month + "." + date_end.Year;


            var reportdata = db.ViewРасходГСМ.Where(x => x.Дата_рейса> date_start && x.Дата_рейса < date_end);

            reportdata = reportdata.OrderBy(x => x.Дата_рейса);

            float sum = 0;
            foreach (ViewРасходГСМ x in reportdata) sum += x.Расход_ГСМ;
            ViewBag.sum = sum;

            return View(reportdata.ToList());
        }

        public ActionResult ChoosePeriod()
        {
            DateTime date_start = DateTime.Now.AddMonths(-1) ;
            DateTime date_end = DateTime.Now;

            ViewBag.date_start = "" + date_start.Year + "-" + (date_start.Month < 10 ? "0" : "") + date_start.Month + "-" + (date_start.Day < 10 ? "0" : "") + date_start.Day;
            ViewBag.date_end = "" + date_end.Year + "-" + (date_end.Month < 10 ? "0" : "") + date_end.Month + "-" + (date_end.Day < 10 ? "0" : "") + date_end.Day;


            return View();

        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Putilin2018/Views/ViewРасходГСМ/ChoosePeriod.cshtml
@{
    ViewBag.Title = "Выбор  периода";
}

<h2>Выбор  периода</h2>

@using (Html.BeginForm("Index", "ViewРасходГСМ", FormMethod.Post))
{
    @*<input type="hidden" value="@ViewBag.BookId" name="BookId" />*@
    <table>
        <tr>
            <td><p>Начало периода: </p></td>
            <td><input type="date" name="date_start" value="@ViewBag.date_start"/> </td>
        </tr>
        <tr>
            <td><p>Окончание периода:</p></td>
            <td><input type="date" name="date_end" value="@ViewBag.date_end"/> </td>
        </tr>
        <tr>
            <td><input type="submit" value="Вывести отчет" /> </td>
            <td></td>
        </tr>
    </table>
}

Putilin2018/Views/ViewРасходГСМ/Index.cshtml
@model IEnumerable<Putilin2018.Models.ViewРасходГСМ>

@{
    ViewBag.Title = "Список рейсов";
}

<h2>Список рейсов c @ViewBag.date_start по @ViewBag.date_start</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="table">
    <tr>
        <th>Дата_рейса</th><th>Название_задачи</th><th>Название_группы</th><th>Расход_ГСМ</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Дата_рейса)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Название_задачи)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Название_группы)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Расход_ГСМ)
        </td>

        <td>
            @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
        </td>
    </tr>
}
    <tr>
        <th></th>
        <th></th>
        <th></th>
        <th>@ViewBag.sum</th>
    </tr>
</table>
@Html.ActionLink("К списку отчетов", "Reports", "Home") <br>